"test2.in", line 33: Tab command not at start of line at symbol "\t1"

"test2.in", line 37: Syntax error at symbol "+"

"test2.in", line 38: Closing parenthesis expected at symbol "="

"test2.in", line 39: Syntax error at symbol "="

"test2.in", line 45: Syntax error at symbol ":"

"test2.in", line 46: \end does not match \begin at symbol
        "\end{axdef}"

"test2.in", line 50: \end does not match \begin at symbol "\end{zed}"

"test2.in", line 54: Syntax error at symbol "\forall"

"test2.in", line 61: Opening parenthesis expected at symbol "\exists"

"test2.in", line 67: Syntax error at symbol ":"

"test2.in", line 73: Decoration ignored in schema def at symbol
        "\defs"

"test2.in", line 76: Syntax error at symbol "''"

"test2.in", line 83: Syntax error at end of file

